export const HELLYEAH_TRACKER_ID =
  process.env.NEXT_PUBLIC_HELLYEAH_TRACKER_ID ||
  "019fac52-9342-7000-be75-c7819cde34f8";

export const HELLYEAH_SERVER_TRACKER_ID =
  process.env.HELLYEAH_TRACKER_ID || HELLYEAH_TRACKER_ID;
