[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  COREPACK_ENABLE = "true"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_GA_ID,NEXT_PUBLIC_AD_SLOT_TOP,NEXT_PUBLIC_AD_SLOT_BOTTOM"
